### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by TarasGit** [oldbootz/shoppinglist#1]
I get an error when I try to recompile client.min.js file from Reactjs-files with webpack. It fails with error-code:

ERROR in ./js/client.js
Module build failed: SyntaxError: /home/taras/Programming/package.json: Error while parsing JSON - Unexpected end of JSON input
    at Object.parse (native)
    at ConfigChainBuilder.addConfig (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:150:65)
    at ConfigChainBuilder.findConfigs (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:102:30)
    at buildConfigChain (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at OptionManager.init (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at File.initOptions (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/taras/Programming/ReactJS/test/shoppinglist/node_modules/babel-loader/lib/index.js:163:20)

I would appreciate any hint how to solve this issue.

**Comment by TarasGit** [comment]
Solved the problem. 
I had wrong PATH set, so that webpack took also another webpack.config.js file. 
Sorry for disturbing you;)
